#!/usr/bin/env python3
"""
Download HW/LW tide predictions from tidetimes.co.uk for UK/Ireland stations.
Reads station list from missing_stations.json (generated by find_missing_tidetimes.py).
Downloads ~15 months of daily HW/LW data per station.
Times are in UK local time (GMT/BST).

Crash-safe:
- Skips stations that already have a complete JSON file (>1000 bytes)
- Writes progress.json after each station (current index, stats)
- Logs to download.log with timestamps
- Can be restarted at any time — picks up where it left off
"""

import os
import re
import json
import time
import sys
import logging
import requests
from datetime import datetime, timedelta

OUTPUT_DIR = '/home/oliver/water_levels/UK_tidetimes'
MISSING_JSON = os.path.join(OUTPUT_DIR, 'missing_stations.json')
PROGRESS_FILE = os.path.join(OUTPUT_DIR, 'download_progress.json')
LOG_FILE = os.path.join(OUTPUT_DIR, 'download.log')

HEADERS = {
    'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36',
    'Accept': 'text/html,application/xhtml+xml',
}

START_DATE = datetime(2025, 1, 1)
END_DATE = datetime(2026, 12, 31)


def setup_logging():
    """Configure logging to file and stdout."""
    logger = logging.getLogger('tidetimes')
    logger.setLevel(logging.INFO)
    # File handler (append mode — survives restarts)
    fh = logging.FileHandler(LOG_FILE, mode='a')
    fh.setFormatter(logging.Formatter('%(asctime)s  %(message)s', datefmt='%Y-%m-%d %H:%M:%S'))
    logger.addHandler(fh)
    # Stdout
    sh = logging.StreamHandler(sys.stdout)
    sh.setFormatter(logging.Formatter('%(message)s'))
    logger.addHandler(sh)
    return logger


def safe_filename(name):
    """Convert station name to safe filename."""
    return name.replace(' ', '_').replace('/', '_').replace("'", '').replace('"', '')


def parse_hwlw(html, date_str):
    """Parse HW/LW data from tidetimes.co.uk daily page."""
    entries = []
    pattern = (
        r'<dt>(High Tide|Low Tide):</dt>\s*<dd>(\d{2}:\d{2})</dd>\s*'
        r'<dt>Height:</dt>\s*<dd>([\d.]+)m</dd>'
    )
    for m in re.finditer(pattern, html):
        tide_type = 'HW' if m.group(1) == 'High Tide' else 'LW'
        entries.append({
            'date': date_str,
            'time': m.group(2),
            'height_m': float(m.group(3)),
            'type': tide_type,
        })
    return entries


def save_progress(idx, total, station_name, status, stats, day_progress=None):
    """Write progress file for crash recovery."""
    progress = {
        'last_update': datetime.now().isoformat(),
        'current_index': idx,
        'total_stations': total,
        'current_station': station_name,
        'status': status,
        'completed': stats['completed'],
        'skipped': stats['skipped'],
        'failed': stats['failed'],
        'json_files': len([f for f in os.listdir(OUTPUT_DIR) if f.endswith('.json') and f != 'missing_stations.json']),
        'task': 'download_tidetimes_uk — Download HW/LW von tidetimes.co.uk fuer alle fehlenden UK/Irland-Stationen',
        'next_step': 'Nach Abschluss: python3 batch/batch_utide_uk_tidetimes.py',
    }
    if day_progress:
        progress['day_progress'] = day_progress
    with open(PROGRESS_FILE, 'w') as f:
        json.dump(progress, f, indent=2)


def download_station(station, logger, progress_cb=None):
    """Download all daily HW/LW data for one station."""
    slug = station['slug']
    name = station['name']
    safe_name = safe_filename(name)
    json_path = os.path.join(OUTPUT_DIR, f'{safe_name}.json')

    # Skip if already downloaded
    if os.path.exists(json_path) and os.path.getsize(json_path) > 1000:
        with open(json_path) as f:
            data = json.load(f)
        n = len(data.get('entries', []))
        logger.info(f"  schon vorhanden ({n} Eintraege)")
        return 'skipped'

    all_entries = []
    current = START_DATE
    total_days = (END_DATE - START_DATE).days + 1
    day_count = 0
    errors = 0
    consecutive_404 = 0

    while current <= END_DATE:
        date_str = current.strftime('%Y-%m-%d')
        url_date = current.strftime('%Y%m%d')
        url = f'https://www.tidetimes.co.uk/{slug}-tide-times-{url_date}'

        for attempt in range(3):
            try:
                r = requests.get(url, headers=HEADERS, timeout=15)
                if r.status_code == 200:
                    entries = parse_hwlw(r.text, date_str)
                    all_entries.extend(entries)
                    consecutive_404 = 0
                    break
                elif r.status_code == 404:
                    consecutive_404 += 1
                    break
                else:
                    if attempt < 2:
                        time.sleep(2)
            except Exception:
                if attempt < 2:
                    time.sleep(2)
                else:
                    errors += 1

        # If 30+ consecutive 404s in the future, stop early
        if consecutive_404 >= 30 and current > datetime.now():
            break

        day_count += 1
        if day_count % 60 == 0:
            logger.info(f"  {day_count}/{total_days} Tage, {len(all_entries)} Eintraege...")
            if progress_cb:
                progress_cb(f"{day_count}/{total_days} Tage, {len(all_entries)} Eintraege")

        current += timedelta(days=1)
        time.sleep(0.25)

    if not all_entries:
        logger.info(f"  KEINE DATEN")
        return 'failed'

    # Remove duplicates
    seen = set()
    unique_entries = []
    for e in all_entries:
        key = (e['date'], e['time'], e['type'])
        if key not in seen:
            seen.add(key)
            unique_entries.append(e)
    unique_entries.sort(key=lambda x: x['date'] + ' ' + x['time'])

    data = {
        'name': name,
        'lat': station['lat'],
        'lon': station['lon'],
        'timezone': 'Europe/London',
        'entries': unique_entries,
    }

    with open(json_path, 'w') as f:
        json.dump(data, f)

    n_hw = sum(1 for e in unique_entries if e['type'] == 'HW')
    n_lw = sum(1 for e in unique_entries if e['type'] == 'LW')
    first = unique_entries[0]['date'] if unique_entries else '?'
    last = unique_entries[-1]['date'] if unique_entries else '?'
    logger.info(f"  {len(unique_entries)} Eintraege ({n_hw} HW, {n_lw} LW, {first} - {last})")
    if errors:
        logger.info(f"  {errors} Fehler")
    return 'completed'


def load_stations():
    """Load station list from missing_stations.json."""
    if not os.path.exists(MISSING_JSON):
        print(f"FEHLER: {MISSING_JSON} nicht gefunden!")
        print("Erst py/find_missing_tidetimes.py ausfuehren.")
        sys.exit(1)
    with open(MISSING_JSON) as f:
        return json.load(f)


def main():
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    logger = setup_logging()

    stations = load_stations()

    logger.info("=" * 70)
    logger.info("Download HW/LW Tide Data -- UK/Ireland (tidetimes.co.uk)")
    logger.info(f"Gestartet: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    logger.info("=" * 70)
    logger.info(f"Stationen: {len(stations)}")
    logger.info(f"Zeitraum: {START_DATE.date()} bis {END_DATE.date()}")
    logger.info("")

    stats = {'completed': 0, 'skipped': 0, 'failed': 0}

    for i, station in enumerate(stations):
        logger.info(f"[{i+1:3d}/{len(stations)}] {station['name']} ({station['slug']})")

        def progress_cb(day_info, _i=i, _name=station['name']):
            save_progress(_i, len(stations), _name, 'downloading', stats, day_progress=day_info)

        save_progress(i, len(stations), station['name'], 'downloading', stats)

        result = download_station(station, logger, progress_cb=progress_cb)
        stats[result] = stats.get(result, 0) + 1

        save_progress(i, len(stations), station['name'], result, stats)
        logger.info("")

    logger.info("=" * 70)
    logger.info(f"FERTIG: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    logger.info(f"Ergebnis: {stats['completed']} neu, {stats['skipped']} uebersprungen, {stats['failed']} fehlgeschlagen")

    save_progress(len(stations), len(stations), 'DONE', 'finished', stats)


if __name__ == '__main__':
    main()
